import {DEFAULTS, compare, validateMission} from "./engine.js";
const $=id=>document.getElementById(id);let params=structuredClone(DEFAULTS),results=null,timer=null,kits={available:4,energy:1.5,mass:7},drone={available:true,payload:10,range:70,speed:55,prep:12,maxWind:45},missions=[];
const communities=[{name:"Mugema",x:75,y:25,pop:430,distance:18,need:2.2,energy:.3,vulnerable:72,health:true,water:false},{name:"Nante",x:73,y:76,pop:610,distance:26,need:3.1,energy:.8,vulnerable:95,health:true,water:true},{name:"Mopeia",x:20,y:25,pop:350,distance:22,need:1.6,energy:.5,vulnerable:41,health:false,water:true}];
const ids=["cloud","wind","rain","panelDamage","roadsClose","flightWindow","solarKw","solarEfficiency","batteryKwh","initialSoc","reserve","maxDischargeKw","biomassKw","biomassKg","specificConsumption","biomassEfficiency","healthUptimeTarget","commsUptimeTarget","dailyWaterTargetLitres","maxCriticalBlackoutMinutes"];
function loadInputs(){const c=$("loadInputs");c.innerHTML=params.loads.map(l=>`<label class="load-input"><span>${l.nome}<small> · ${l.start}—${l.end}h</small></span><input data-load="${l.id}" type="number" min="0" max="50" step=".1" value="${l.power}" aria-label="Potência de ${l.nome}"></label>`).join("");c.querySelectorAll("input").forEach(i=>i.onchange=()=>{params.loads.find(l=>l.id===i.dataset.load).power=+i.value;run()})}
function read(){ids.forEach(id=>params[id]=Math.max(0,+$(id).value));params.scenario=$("scenario").value;params.strategy=$("strategy").value;params.biomassAvailable=$("biomassAvailable").checked;params.wetFuel=$("wetFuel").checked;return params}
function run(){read();results=compare(params);render();}
function fmt(v,d=1){return Number(v).toLocaleString("pt-PT",{maximumFractionDigits:d})}
function summaryHtml(s){const state=v=>v?"Cumprido":"Não cumprido";return `<span>Índice de resiliência<b>${fmt(s.resilience)}%</b></span><span>Blackout crítico<b>${s.firstBlackout===null?"Não ocorreu":`Hora ${s.firstBlackout}`}</b></span><span>Sobrevivência da saúde<b>${state(s.survival.health)}</b></span><span>Sobrevivência das comunicações<b>${state(s.survival.comms)}</b></span><span>Meta diária de água<b>${state(s.survival.water)}</b></span><span>Sobrevivência conjunta<b>${state(s.survival.joint)}</b></span><span>Blackout contínuo máximo<b>${s.maxCriticalBlackoutMinutes} min</b></span><span>Água por dia<b>${s.waterByDay.map(v=>fmt(v,0)).join(" / ")} L</b></span>`}
function services(result,t){const r=result.series[t];return [["Saúde","saude"],["Água","agua"],["Comunicação","comms"]].map(([n,id])=>`<span class="${(r.served[id]||0)<.01?'off':''}">${n}</span>`).join("")}
function render(){const c=results.convencional.summary,r=results.resiliente.summary;$("convResults").innerHTML=summaryHtml(c);$("resResults").innerHTML=summaryHtml(r);$("convState").textContent=c.firstBlackout===null?"OPERACIONAL":`BLACKOUT H${c.firstBlackout}`;$("resState").textContent=r.firstBlackout===null?"OPERACIONAL":`BLACKOUT H${r.firstBlackout}`;$("convState").className=c.firstBlackout===null?"":"blackout";$("resState").className=r.firstBlackout===null?"":"blackout";drawTimeline();renderEvents();updateHour(+$('timeSlider').value);renderMap();const advantage=r.resilience-c.resilience;$("decisionTitle").textContent=advantage>0?`A resiliência aumenta ${fmt(advantage)} pontos`:`O sistema precisa de reforço`;$("decisionText").textContent=`Com os recursos actuais, a biomassa preserva a reserva estratégica e o controlador sacrifica primeiro cargas não críticas. Autonomia crítica aproximada: ${r.firstBlackout??72} horas.`}
function drawTimeline(){const canvas=$("timelineChart"),w=canvas.clientWidth,h=canvas.clientHeight,dpr=devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;const x=canvas.getContext("2d");x.scale(dpr,dpr);x.clearRect(0,0,w,h);const pad={l:32,r:10,t:10,b:22},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b,max=Math.max(10,...results.resiliente.series.map(v=>Math.max(v.demand,v.solar,v.bio,v.criticalUnserved)))*1.15;x.font="9px system-ui";x.fillStyle="#68736b";for(let i=0;i<5;i++){const y=pad.t+ph*i/4;x.strokeStyle="#e5e9e5";x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();x.fillText(fmt(max*(1-i/4),0),2,y+3)}[0,24,48,72].forEach(v=>x.fillText(`${v}h`,pad.l+pw*v/72-7,h-4));const line=(key,color,scale=max,source=results.resiliente.series)=>{x.beginPath();source.forEach((v,i)=>{const px=pad.l+pw*i/71,py=pad.t+ph-v[key]/scale*ph;i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle=color;x.lineWidth=2;x.stroke()};line("demand","#cb5b4c");line("solar","#e4ae3d");line("bio","#276840");x.setLineDash([4,3]);line("soc","#4c80a0",100);x.setLineDash([]);line("criticalUnserved","#171717")}
function renderEvents(){const rail=$("eventRail");rail.innerHTML=results.resiliente.events.map((e,i)=>`<span style="left:${e.t/72*100}%;top:${5+(i%2)*13}px">${e.label}</span>`).join("")}
function updateHour(t){$("timeLabel").textContent=`Hora ${t}`;$("convServices").innerHTML=services(results.convencional,t);$("resServices").innerHTML=services(results.resiliente,t);const rr=results.resiliente.series[t];if(rr.criticalUnserved>0){$("decisionTitle").textContent="Procura crítica não servida";$("decisionText").textContent=`Na hora ${t}, faltam ${fmt(rr.criticalUnserved)} kWh críticos. Reveja bateria, biomassa ou prioridades.`}}
function priority(c){return(c.vulnerable*(c.health?3:c.water?2:1)*(1+Math.max(0,c.need-c.energy)))/(c.distance*Math.max(.2,c.need))}
function renderMap(){const map=$("communityMap"),recommended=[...communities].sort((a,b)=>priority(b)-priority(a))[0];map.innerHTML='<span class="hub">HUB</span>'+communities.map(c=>`<button class="community ${c.energy<c.need?'critical':''}" data-community="${c.name}" style="left:${c.x}%;top:${c.y}%">${c.name}<small>${fmt(c.energy)} kWh</small></button>`).join("")+`<span class="map-drone" id="mapDrone" style="left:50%;top:50%">▲</span>`;map.querySelectorAll(".community").forEach(b=>b.onclick=()=>recommend(b.dataset.community));recommend(recommended.name)}
function recommend(name){const c=communities.find(x=>x.name===name),weather={wind:params.wind,hour:+$("timeSlider").value,flightWindow:params.flightWindow},v=validateMission(drone,c,weather,kits);$("recommendation").dataset.name=name;$("recommendation").innerHTML=`<b>${name}</b> · prioridade ${fmt(priority(c),2)}<br>${c.pop} pessoas · ${c.distance} km · ${c.vulnerable} vulneráveis<br><strong>${v.ok?`Missão viável · ${fmt(v.time,0)} min`:`Bloqueada: ${v.errors.join("; ")}`}</strong>`;$("flightStatus").textContent=v.ok?"Janela segura":"Voo bloqueado";$("dispatchBtn").disabled=!v.ok}
function dispatch(){const c=communities.find(x=>x.name===$("recommendation").dataset.name),weather={wind:params.wind,hour:+$("timeSlider").value,flightWindow:params.flightWindow},v=validateMission(drone,c,weather,kits);if(!v.ok)return;c.energy+=kits.energy;kits.available--;missions.push({hora:+$("timeSlider").value,community:c.name,energy:kits.energy});const d=$("mapDrone");d.style.left=c.x+"%";d.style.top=c.y+"%";$("missionLog").textContent=`Kit entregue em ${c.name}. Energia: +${kits.energy} kWh. Kits restantes: ${kits.available}. Serviço crítico recuperado.`;setTimeout(renderMap,1900)}
function inject(){const f=$("failure").value;if(!f)return;if(f==="panels50")params.panelDamage=50;if(f==="lowBattery")params.initialSoc=35;if(f==="generator")params.biomassAvailable=false;if(f==="wetFuel")params.wetFuel=true;if(f==="healthDouble")params.loads.find(l=>l.id==="saude").power*=2;if(f==="waterDouble")params.loads.find(l=>l.id==="agua").power*=2;if(f==="lateFlight")params.flightWindow=Math.min(72,params.flightWindow+18);syncControls();$("failureLog").textContent=`Falha aplicada na hora ${$("timeSlider").value}. O restante plano foi recalculado.`;run()}
function syncControls(){ids.forEach(id=>{if($(id))$(id).value=params[id]});$("biomassAvailable").checked=params.biomassAvailable;$("wetFuel").checked=params.wetFuel;loadInputs()}
function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
async function monteCarlo(){const n=+$("mcRuns").value,random=rng(+$('seed').value),conv=[],res=[];$("mcBtn").disabled=true;for(let i=0;i<n;i++){const p=structuredClone(read());p.cloud=Math.min(100,Math.max(20,p.cloud+(random()-.5)*35));p.panelDamage=Math.min(90,Math.max(0,p.panelDamage+(random()-.5)*45));p.initialSoc=Math.min(100,Math.max(20,p.initialSoc+(random()-.5)*35));p.biomassKg*=.55+random()*.8;p.wetFuel=random()<.25;p.biomassAvailable=random()>.12;p.loads.filter(l=>l.critical).forEach(l=>l.surge*=.85+random()*.55);const out=compare(p);conv.push(out.convencional.summary);res.push(out.resiliente.summary);if(i%20===0){$("mcProgress").value=i/n*100;await new Promise(requestAnimationFrame)}}$("mcProgress").value=100;const rate=(a,key)=>a.filter(s=>s.survival[key]).length/n*100,metrics=[['health','Saúde'],['comms','Comunicações'],['water','Meta de água'],['joint','Três serviços']];const cp=rate(conv,'joint'),rp=rate(res,'joint');$("convProbability").textContent=fmt(cp)+"%";$("resProbability").textContent=fmt(rp)+"%";$("convBar").style.width=cp+"%";$("resBar").style.width=rp+"%";$("survivalMatrix").innerHTML=`<span>Critério</span><b>Convencional</b><b>Resiliente</b>${metrics.map(([key,label])=>`<span>${label}</span><strong>${fmt(rate(conv,key))}%</strong><strong>${fmt(rate(res,key))}%</strong>`).join('')}`;const failed=metrics.filter(([key])=>rate(res,key)===0).map(([,label])=>label.toLowerCase());$("mcConclusion").textContent=`Com os parâmetros actuais, o sistema convencional satisfez todos os critérios em ${fmt(cp)}% dos cenários e o resiliente em ${fmt(rp)}%.${rp===0?` O resultado permanece 0% porque nenhum cenário satisfez simultaneamente os limites; critérios com taxa nula: ${failed.join(', ')||'combinação conjunta'}.`:''} Semente: ${$('seed').value}.`;drawMc(conv,res);$("mcBtn").disabled=false}
function drawMc(conv,res){const c=$("mcChart"),w=c.clientWidth,h=c.clientHeight,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;const x=c.getContext("2d");x.scale(d,d);x.clearRect(0,0,w,h);const bins=12,count=a=>bins?Array.from({length:bins},(_,i)=>a.filter(s=>(s.firstBlackout??72)>=i*6&&(s.firstBlackout??72)<(i+1)*6).length):[];const ca=count(conv),ra=count(res),max=Math.max(1,...ca,...ra),bw=w/bins;x.fillStyle="#777";ca.forEach((v,i)=>x.fillRect(i*bw,h-v/max*(h-20),bw*.38,v/max*(h-20)));x.fillStyle="#276840";ra.forEach((v,i)=>x.fillRect(i*bw+bw*.42,h-v/max*(h-20),bw*.38,v/max*(h-20)))}
function exportCsv(){if(!results)return;const rows=["hora,sistema,solar_kW,biomassa_kW,procura_kW,bateria_pct,energia_nao_servida_kWh"];for(const type of ["convencional","resiliente"])results[type].series.forEach(r=>rows.push([r.t,type,r.solar,r.bio,r.demand,r.soc,r.unserved].join(",")));const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.join("\n")],{type:"text/csv"}));a.download="resiliencia-72h.csv";a.click();URL.revokeObjectURL(a.href)}
async function jury(){const btn=$("juryBtn");btn.disabled=true;$("scenario").value="normal";run();for(const [wait,action] of [[1400,()=>{$("scenario").value="severo";run()}],[1400,()=>{$("stormBtn").click()}],[1300,()=>{$("panelDamage").value=50;run()}],[1700,()=>{$("timeSlider").value=30;updateHour(30)}],[1400,()=>{$("wind").value=35;params.wind=35;renderMap()}],[1200,dispatch],[1700,monteCarlo]]){await new Promise(r=>setTimeout(r,wait));action()}btn.disabled=false;document.querySelector("footer").scrollIntoView({behavior:"smooth"})}
ids.forEach(id=>$(id).onchange=run);$("scenario").onchange=run;$("strategy").onchange=run;$("biomassAvailable").onchange=run;$("wetFuel").onchange=run;$("runBtn").onclick=run;$("stormBtn").onclick=()=>{$("scenario").value="severo";run();$("timeSlider").value=2;updateHour(2)};$("timeSlider").oninput=e=>updateHour(+e.target.value);$("playBtn").onclick=()=>{if(timer){clearInterval(timer);timer=null;$("playBtn").textContent="▶";return}$("playBtn").textContent="Ⅱ";timer=setInterval(()=>{let t=+$('timeSlider').value+1;if(t>71){clearInterval(timer);timer=null;t=0;$("playBtn").textContent="▶"}$("timeSlider").value=t;updateHour(t)},120)};$("dispatchBtn").onclick=dispatch;$("injectBtn").onclick=inject;$("mcBtn").onclick=monteCarlo;$("exportBtn").onclick=exportCsv;$("juryBtn").onclick=jury;$("resetBtn").onclick=()=>{params=structuredClone(DEFAULTS);syncControls();run()};window.onresize=()=>{if(results)drawTimeline()};syncControls();run();
