export const LOADS=[
 {id:"comms",name:"Radio/VHF, LEDs, telemoveis e controlo",priority:1,dailyKwh:.55},
 {id:"cold",name:"Conservacao de medicamentos",priority:1,dailyKwh:.9},
 {id:"pump",name:"Agua do deposito elevado",priority:1,dailyKwh:.5,schedule:[6,8]},
 {id:"secondary",name:"Iluminacao adicional e carregamentos",priority:2,dailyKwh:.3,schedule:[18,24]}
];
export const DEFAULTS={duration:72,timeStepHours:.25,solarKwp:2,batteryKwh:10,initialSoc:100,usableBatteryPercent:80,deliveryEfficiency:90,chargeEfficiency:94,panelDamage:0,cloud:100,inverterKw:2,inverterIdleKw:.01,waterPeakM:3.4,floodPeakHour:30,fixedCabinetM:1.2,guideHeightM:4.5,moduleMassKg:360,moduleCgHeightM:.65,drumCount:4,drumLitres:200,drumDiameterM:.58,drumLengthM:.9,requiredDisplacementLitresPerKg:2,cableTravelM:3.1,debrisRisk:15,guideFailure:false,sensorFailure:false,controllerFailure:false,leakage:false,portablePackKwh:.65,portablePackMaxKw:.12,loadMultiplier:1,batteryDegradation:0,tankCapacityLitres:1000,initialTankLitres:1000,waterUseLitresDay:300,pumpLitresPerKwh:2000,thermalStorageHours:8};
const clamp=(v,min,max)=>Math.min(max,Math.max(min,Number.isFinite(+v)?+v:min));
export function normalize(input={}){const p={...DEFAULTS,...structuredClone(input)};for(const key of ["guideFailure","sensorFailure","controllerFailure","leakage"])p[key]=Boolean(p[key]);p.duration=clamp(p.duration,.25,720);p.timeStepHours=clamp(p.timeStepHours,.05,1);p.solarKwp=clamp(p.solarKwp,0,100);p.batteryKwh=clamp(p.batteryKwh,.1,1000);p.initialSoc=clamp(p.initialSoc,0,100);p.usableBatteryPercent=clamp(p.usableBatteryPercent,0,100);p.deliveryEfficiency=clamp(p.deliveryEfficiency,1,100);p.chargeEfficiency=clamp(p.chargeEfficiency,1,100);p.panelDamage=clamp(p.panelDamage,0,100);p.cloud=clamp(p.cloud,0,100);p.inverterKw=clamp(p.inverterKw,.01,100);p.inverterIdleKw=clamp(p.inverterIdleKw,0,1);p.waterPeakM=clamp(p.waterPeakM,0,20);p.floodPeakHour=clamp(p.floodPeakHour,.25,p.duration-.25);p.fixedCabinetM=clamp(p.fixedCabinetM,0,10);p.guideHeightM=clamp(p.guideHeightM,p.fixedCabinetM+.1,20);p.moduleMassKg=clamp(p.moduleMassKg,1,10000);p.moduleCgHeightM=clamp(p.moduleCgHeightM,.05,10);p.drumCount=Math.round(clamp(p.drumCount,1,20));p.drumLitres=clamp(p.drumLitres,1,5000);p.drumDiameterM=clamp(p.drumDiameterM,.1,5);p.drumLengthM=clamp(p.drumLengthM,.1,10);p.requiredDisplacementLitresPerKg=clamp(p.requiredDisplacementLitresPerKg,1,5);p.cableTravelM=clamp(p.cableTravelM,0,20);p.debrisRisk=clamp(p.debrisRisk,0,100);p.portablePackKwh=clamp(p.portablePackKwh,0,100);p.portablePackMaxKw=clamp(p.portablePackMaxKw,0,10);p.loadMultiplier=clamp(p.loadMultiplier,0,10);p.batteryDegradation=clamp(p.batteryDegradation,0,p.usableBatteryPercent);p.tankCapacityLitres=clamp(p.tankCapacityLitres,0,100000);p.initialTankLitres=clamp(p.initialTankLitres,0,p.tankCapacityLitres);p.waterUseLitresDay=clamp(p.waterUseLitresDay,0,100000);p.pumpLitresPerKwh=clamp(p.pumpLitresPerKwh,1,100000);p.thermalStorageHours=clamp(p.thermalStorageHours,0,720);return p}
const daylight=h=>h>=6&&h<=18?Math.sin((h-6)/12*Math.PI):0,active=(load,h)=>!load.schedule||(h>=load.schedule[0]&&h<load.schedule[1]);
export function floodLevel(t,p){return t<=p.floodPeakHour?p.waterPeakM*(t/p.floodPeakHour)**1.45:p.waterPeakM*Math.max(0,1-(t-p.floodPeakHour)/(p.duration-p.floodPeakHour))**1.2}
function cylinderDraft(volumeM3,count,diameter,length){const r=diameter/2,target=volumeM3/(count*length),area=h=>r*r*Math.acos(clamp((r-h)/r,-1,1))-(r-h)*Math.sqrt(Math.max(0,2*r*h-h*h));let low=0,high=diameter;for(let i=0;i<60;i++){const mid=(low+high)/2;if(area(mid)<target)low=mid;else high=mid}return Math.min(diameter,(low+high)/2)}
export function simulate(input={}){
 const p=normalize(input),dt=p.timeStepHours,steps=Math.round(p.duration/dt),series=[],events=[],usableFraction=Math.max(0,p.usableBatteryPercent/100-p.batteryDegradation/100),floor=p.batteryKwh*(1-usableFraction),eff=p.deliveryEfficiency/100,totalBuoyancyLitres=p.drumCount*p.drumLitres,displacementRatio=totalBuoyancyLitres/p.moduleMassKg;
 const draftM=cylinderDraft(Math.min(totalBuoyancyLitres,p.moduleMassKg)/1000,p.drumCount,p.drumDiameterM,p.drumLengthM),freeboardM=Math.max(0,p.drumDiameterM-draftM),buoyancyReserveKg=Math.max(0,totalBuoyancyLitres-p.moduleMassKg),lateralCapacityN=Math.max(0,buoyancyReserveKg*9.81*Math.max(.05,freeboardM)/(p.moduleCgHeightM+.1)),stableBase=displacementRatio>=p.requiredDisplacementLitresPerKg&&draftM<p.drumDiameterM&&p.moduleCgHeightM<1&&lateralCapacityN>=250;
 let battery=Math.min(p.batteryKwh,p.batteryKwh*p.initialSoc/100),pack=p.portablePackKwh,tank=p.initialTankLitres,thermal=p.thermalStorageHours,isolated=false,firstServiceFailure=null,previousFloat=false,previousIsolation=false,previousFallback=false;const preserved={comms:0,cold:0,pump:0};
 for(let i=0;i<steps;i++){
  const t=i*dt,h=t%24,water=floodLevel(t,p),floats=water>=p.fixedCabinetM+draftM,moduleY=floats?Math.max(p.fixedCabinetM,Math.min(water-draftM,p.guideHeightM)):p.fixedCabinetM,travel=Math.max(0,moduleY-p.fixedCabinetM),guideBlocked=p.guideFailure||(p.debrisRisk>75&&floats),stable=stableBase&&!guideBlocked,cableExceeded=travel>p.cableTravelM+1e-9,guideExceeded=water>p.guideHeightM+draftM,cabinetSubmerged=water>=p.fixedCabinetM,leakTrip=p.leakage&&water>.15,unsafe=floats&&(!stable||cableExceeded||guideExceeded),manualFallback=p.sensorFailure||p.controllerFailure;
  isolated=isolated||unsafe||leakTrip;if(cabinetSubmerged&&!events.some(e=>e.kind==="submersion"))events.push({t,label:"Agua atinge o equipamento fixo; nucleo anfibio assume protecao",kind:"submersion"});if(floats&&!previousFloat)events.push({t,label:"Modulo inicia flutuacao controlada",kind:"float"});if(manualFallback&&!previousFallback)events.push({t,label:"Falha de controlo: P2 cortada; P1 em modo manual",kind:"fallback"});if(isolated&&!previousIsolation)events.push({t,label:"Isolamento eletrico antes do limite mecanico",kind:"isolate"});previousFloat=floats;previousIsolation=isolated;previousFallback=manualFallback;
  const solarPotential=p.solarKwp*daylight(h)*(1-p.cloud/100)*(1-p.panelDamage/100)*.82,solar=isolated?0:solarPotential,coldFactor=(t%2)<.75?1.8:.52,desired=LOADS.map(l=>({...l,demand:active(l,h)?l.dailyKwh/(l.schedule?(l.schedule[1]-l.schedule[0]):24)*p.loadMultiplier*(l.id==="cold"?coldFactor:1):0})),soc=battery/p.batteryKwh,mode=manualFallback?"manual_p1":soc>=.5?"normal":soc>=.3?"racionamento":"sobrevivencia",allowed=desired.filter(l=>l.priority===1||(mode==="normal"&&!manualFallback));
  let served={comms:0,cold:0,pump:0,secondary:0,emergencyLight:0},direct=0,batteryOut=0,charge=0,packOut=0;if(isolated){const emergencyDemand=Math.min(p.portablePackMaxKw,desired.find(l=>l.id==="comms").demand+.02);packOut=Math.min(emergencyDemand,pack/dt);served.comms=Math.min(desired.find(l=>l.id==="comms").demand,packOut);served.emergencyLight=Math.max(0,packOut-served.comms);pack=Math.max(0,pack-packOut*dt)}else{const demand=allowed.reduce((s,l)=>s+l.demand,0),inverterIdle=p.inverterIdleKw;direct=Math.min(demand+inverterIdle,solar);const remaining=demand+inverterIdle-direct,deliverable=Math.max(0,battery-floor)*eff/dt;batteryOut=Math.min(remaining,p.inverterKw,deliverable);battery=Math.max(0,battery-batteryOut*dt/eff);let supply=Math.max(0,direct+batteryOut-inverterIdle);allowed.forEach(l=>{served[l.id]=Math.min(l.demand,supply);supply-=served[l.id]});const surplus=Math.max(0,solar-direct);charge=Math.min(surplus,p.inverterKw,(p.batteryKwh-battery)/dt)*dt*p.chargeEfficiency/100;battery=Math.min(p.batteryKwh,battery+charge)}
  const pumpEnergy=served.pump*dt,tankAvailable=Math.min(p.tankCapacityLitres,tank+pumpEnergy*p.pumpLitresPerKwh),waterRequested=p.waterUseLitresDay/24*dt,waterDelivered=Math.min(tankAvailable,waterRequested);tank=Math.max(0,tankAvailable-waterDelivered);const commsDemand=desired.find(l=>l.id==="comms").demand,coldDemand=desired.find(l=>l.id==="cold").demand,commsPreserved=served.comms+1e-7>=commsDemand,coldElectrical=served.cold+1e-7>=coldDemand,coldPreserved=coldElectrical||thermal+1e-9>=dt,waterPreserved=waterDelivered+1e-7>=waterRequested;if(!coldElectrical&&thermal>0)thermal=Math.max(0,thermal-dt);const services={comms:commsPreserved,cold:coldPreserved,pump:waterPreserved};for(const id of Object.keys(preserved))if(services[id])preserved[id]++;if(firstServiceFailure===null&&!Object.values(services).every(Boolean))firstServiceFailure=t;
  const p1Demand=desired.filter(l=>l.priority===1).reduce((s,l)=>s+l.demand,0),p1Served=desired.filter(l=>l.priority===1).reduce((s,l)=>s+served[l.id],0),inverterIdleKwh=isolated?0:p.inverterIdleKw*dt,energyInput=direct+batteryOut+packOut,energyAllocated=Object.values(served).reduce((s,v)=>s+v,0);series.push({t,water,moduleY,draftM,freeboardM,lateralCapacityN,floats,stable,guideBlocked,cableExceeded,guideExceeded,manualFallback,isolated,solar,solarPotential,demand:desired.reduce((s,l)=>s+l.demand,0),p1Demand,p1Served,batteryKwh:battery,batteryOut,charge,soc:battery/p.batteryKwh*100,packKwh:pack,packOut,tankLitres:tank,waterRequested,waterDelivered,thermalHours:thermal,mode,served,services,energyInput,energyAllocated,cabinetSubmerged,inverterIdleKwh,guideHeightM:p.guideHeightM,fixedCabinetM:p.fixedCabinetM,drumDiameterM:p.drumDiameterM,drumLengthM:p.drumLengthM});
 }
 const serviceUptime=Object.fromEntries(Object.keys(preserved).map(id=>[id,preserved[id]/steps*100])),p1Success=Object.values(serviceUptime).every(v=>v>=99.99),modeledEnergyKwh=series.reduce((s,r)=>s+r.demand*dt,0),modeledP1EnergyKwh=series.reduce((s,r)=>s+r.p1Demand*dt,0),inverterIdleEnergyKwh=series.reduce((s,r)=>s+r.inverterIdleKwh,0),first24LoadKwh=series.filter(r=>r.t<24).reduce((s,r)=>s+r.demand*dt,0),first24IdleKwh=series.filter(r=>r.t<24).reduce((s,r)=>s+r.inverterIdleKwh,0),initialStoredKwh=Math.min(p.batteryKwh,p.batteryKwh*p.initialSoc/100),availableBatteryKwh=Math.max(0,initialStoredKwh-floor)*eff;
 return {params:p,series,events,summary:{p1Success,serviceUptime,firstP1Failure:firstServiceFailure,finalSoc:series.at(-1).soc,isolated:series.some(r=>r.isolated),manualFallback:series.some(r=>r.manualFallback),maxWater:Math.max(...series.map(r=>r.water)),displacementRatio,draftM,freeboardM,lateralCapacityN,buoyancyPass:stableBase,finalTankLitres:tank,nominalBudgetKwh:LOADS.reduce((s,l)=>s+l.dailyKwh,0)*p.duration/24,modeledEnergyKwh,modeledP1EnergyKwh,inverterIdleEnergyKwh,first24LoadKwh,first24IdleKwh,guaranteedBatteryKwh:p.batteryKwh*(p.usableBatteryPercent/100)*eff,availableBatteryKwh}};
}
export function seeded(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
export function monteCarlo(base,n=500,seed=72026){const p=normalize(base),rnd=seeded(seed),records=[];for(let i=0;i<n;i++){const sample={cloud:clamp(p.cloud-30+rnd()*30,0,100),panelDamage:clamp(p.panelDamage+rnd()*45,0,100),waterPeakM:clamp(p.waterPeakM*(.6+rnd()*1.2),0,20),floodPeakHour:clamp(p.floodPeakHour-12+rnd()*24,.25,p.duration-.25),debrisRisk:clamp(p.debrisRisk-20+rnd()*70,0,100),batteryDegradation:clamp(p.batteryDegradation+rnd()*20,0,p.usableBatteryPercent),loadMultiplier:clamp(p.loadMultiplier*(.9+rnd()*.35),0,10),guideFailure:rnd()<.06,sensorFailure:rnd()<.03,controllerFailure:rnd()<.03,leakage:rnd()<.025};records.push({sample,result:simulate({...p,...sample})})}return records}
