import test, {before,after} from "node:test";
import assert from "node:assert/strict";
import {spawn} from "node:child_process";
import {chromium} from "playwright-core";

let server,browser;
const url="http://127.0.0.1:4173";
before(async()=>{server=spawn(process.execPath,["tests/server.mjs"],{stdio:"ignore"});await new Promise(r=>setTimeout(r,700));browser=await chromium.launch({headless:true,executablePath:"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"})});
after(async()=>{await browser?.close();server?.kill()});
async function pageAt(viewport){const page=await browser.newPage({viewport,acceptDownloads:true});const errors=[];page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});page.on("pageerror",e=>errors.push(e.message));await page.goto(url);await page.waitForSelector("#timelineChart");return {page,errors}}

test("visual redesign preserves the complete interactive inventory",async()=>{const {page,errors}=await pageAt({width:1440,height:900});const ids=[
  "juryBtn","demoPauseBtn","demoResetBtn","exportBtn","stormBtn","runBtn","resetBtn","playBtn","dispatchBtn","injectBtn","mcBtn","optimizeBtn",
  "scenario","strategy","kitType","failure","mcRuns","targetSurvival","cloud","wind","rain","panelDamage","roadsClose","flightWindow",
  "solarKw","solarEfficiency","batteryKwh","initialSoc","reserve","maxDischargeKw","biomassKw","biomassKg","specificConsumption","biomassMin","dailyFuelLimit","biomassAvailable","wetFuel",
  "timeSlider","seed","healthUptimeTarget","commsUptimeTarget","dailyWaterTargetLitres","minimumWaterLitresPerPersonDay","healthUsers","maxCriticalBlackoutMinutes",
  "maxBudget","solarOptMin","solarOptMax","batteryOptMin","batteryOptMax","bioOptMin","bioOptMax","fuelOptMin","fuelOptMax","optKits","costSolar","costBattery","costBiomass","costFuel","costKit",
  "demoStatus","convState","resState","convServices","resServices","convResults","resResults","timelineChart","eventRail","timeLabel","decisionTitle","decisionText",
  "flightStatus","communityMap","missionProgress","missionStatus","recommendation","missionLog","failureLog","mcProgress","survivalMatrix","convProbability","resProbability","convBar","resBar","mcStats","mcSurvivalChart","mcHistogramChart","mcSensitivityChart","mcConclusion","optProgress","optResult","healthRuleTarget","healthAllowed","commsRuleTarget","commsAllowed","blackoutRuleTarget","blackoutAllowed"
];const missing=await page.evaluate(required=>required.filter(id=>!document.getElementById(id)),ids);assert.deepEqual(missing,[]);assert.equal(await page.locator("#loadInputs input").count(),5);assert.equal(await page.locator("details").count(),11);assert.equal(await page.locator("details[open]").count(),0);assert.deepEqual(errors,[]);await page.close()});

for(const [name,viewport] of [["desktop",{width:1440,height:900}],["tablet",{width:820,height:1180}]])test(`renders without overflow or console errors on ${name}`,async()=>{const {page,errors}=await pageAt(viewport);const metrics=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,canvas:[...document.querySelectorAll("canvas")].every(c=>c.width>0&&c.height>0)}));assert.ok(metrics.scrollWidth<=metrics.clientWidth+1,JSON.stringify(metrics));assert.equal(metrics.canvas,true);assert.deepEqual(errors,[]);await page.close()});

for(const [name,viewport] of [["desktop",{width:1440,height:900}],["tablet",{width:820,height:1180}]])test(`timeline event labels do not overlap on ${name}`,async()=>{const {page,errors}=await pageAt(viewport);await page.waitForTimeout(100);const layout=await page.evaluate(()=>{const boxes=[...document.querySelectorAll("#eventRail span")].map(el=>{const r=el.getBoundingClientRect();return {text:el.textContent,left:r.left,right:r.right,top:r.top,bottom:r.bottom}}),playback=document.querySelector(".playback").getBoundingClientRect();const collisions=[];for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];if(a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top)collisions.push([a.text,b.text])}return {collisions,eventBottom:Math.max(...boxes.map(b=>b.bottom)),playbackTop:playback.top}});assert.deepEqual(layout.collisions,[]);assert.ok(layout.eventBottom<=layout.playbackTop,JSON.stringify(layout));assert.deepEqual(errors,[]);await page.close()});

test("timeline play and pause move and freeze the graph playhead",async()=>{const {page,errors}=await pageAt({width:1440,height:900});const pixels=async()=>page.locator("#timelineChart").evaluate(canvas=>{const x=canvas.getContext("2d"),data=x.getImageData(0,0,canvas.width,canvas.height).data;let sum=0;for(let i=0;i<data.length;i+=4)sum=(sum+data[i]*3+data[i+1]*5+data[i+2]*7)>>>0;return sum});const before=await pixels();await page.click("#playBtn");await page.waitForTimeout(500);const runningHour=Number(await page.inputValue("#timeSlider")),during=await pixels();assert.ok(runningHour>=.5);assert.notEqual(during,before);await page.click("#playBtn");const pausedHour=await page.inputValue("#timeSlider"),pausedPixels=await pixels();await page.waitForTimeout(500);assert.equal(await page.inputValue("#timeSlider"),pausedHour);assert.equal(await pixels(),pausedPixels);assert.deepEqual(errors,[]);await page.close()});

test("delivery updates the selected community and protected people",async()=>{const {page,errors}=await pageAt({width:1440,height:900});await page.locator(".parameters details").first().locator("summary").click();await page.fill("#wind","30");await page.fill("#flightWindow","0");await page.fill("#timeSlider","0");await page.selectOption("#kitType","comms");await page.click('[data-community="Mugema"]');const before=await page.locator("#resResults .coverage-unique b").textContent();await page.click("#dispatchBtn");await page.waitForFunction(()=>document.querySelector("#missionStatus")?.textContent.includes("autonomia adicional"),null,{timeout:8000});const log=await page.locator("#missionLog").textContent(),afterValue=await page.locator("#resResults .coverage-unique b").textContent();assert.match(log,/Mugema/);assert.match(log,/0,8 kWh úteis/);assert.notEqual(afterValue,before);assert.deepEqual(errors,[]);await page.close()});

test("CSV values agree with the visible simulation",async()=>{const {page,errors}=await pageAt({width:1440,height:900});const visibleFuel=Number((await page.locator(".biomass-live span").first().locator("b").textContent()).replace(" kg","").replace(",",".")),downloadPromise=page.waitForEvent("download");await page.click("#exportBtn");const download=await downloadPromise,path=await download.path();const fs=await import("node:fs/promises"),csv=await fs.readFile(path,"utf8"),lines=csv.trim().split(/\r?\n/),header=lines[0].split(","),first=lines[1].split(","),resilientHour0=lines[73].split(","),fuelColumn=header.indexOf("combustivel_restante_kg");assert.equal(lines.length,145);assert.equal(first[0],"0");assert.equal(first[1],"convencional");assert.equal(resilientHour0[0],"0");assert.equal(resilientHour0[1],"resiliente");assert.ok(Math.abs(Number(resilientHour0[fuelColumn])-visibleFuel)<.11);assert.equal(await page.locator("#timeLabel").textContent(),"Hora 0");assert.deepEqual(errors,[]);await page.close()});

test("first visible blackout diagnosis uses comparable aggregate values",async()=>{const {page,errors}=await pageAt({width:1440,height:900}),label=await page.locator("#resState").textContent(),match=label.match(/H([\d.]+)/);assert.ok(match,"expected a calculated resilient blackout");const hour=Number(match[1]);await page.locator("#timeSlider").evaluate((el,value)=>{el.value=String(value);el.oninput({target:el})},hour);const text=await page.locator("#decisionText").innerText();assert.match(text,/procura crítica total foi/);assert.match(text,/puderam ser distribuídos/);assert.match(text,/défice conjunto de/);const critical=Number(text.match(/procura crítica total foi ([\d,]+) kW/)[1].replace(",",".")),usable=Number(text.match(/apenas ([\d,]+) kW puderam/)[1].replace(",",".")),affected=Number(text.match(/procura conjunta de ([\d,]+) kW/)[1].replace(",",".")),served=Number(text.match(/receberam ([\d,]+) kW/)[1].replace(",",".")),deficit=Number(text.match(/défice conjunto de ([\d,]+) kW/)[1].replace(",","."));assert.ok(critical>usable);assert.ok(Math.abs((affected-served)-deficit)<.11);assert.deepEqual(errors,[]);await page.close()});

test("preliminary sizing reports evaluated scope and uncertainty",async()=>{const {page,errors}=await pageAt({width:1440,height:900});await page.selectOption("#mcRuns","100");for(const [min,max] of [["solarOptMin","solarOptMax"],["batteryOptMin","batteryOptMax"],["bioOptMin","bioOptMax"],["fuelOptMin","fuelOptMax"]]){const value=await page.inputValue(`#${min}`);await page.fill(`#${max}`,value)}await page.click("#optimizeBtn");await page.waitForFunction(()=>!document.querySelector("#optimizeBtn").disabled,null,{timeout:30000});const heading=await page.locator(".sizing h2").textContent(),text=await page.locator("#optResult").innerText();assert.equal(heading,"Pesquisa preliminar de dimensionamento");assert.match(text,/Combinações avaliadas/);assert.match(text,/Resolução/);assert.match(text,/Melhor configuração inviável/);assert.match(text,/Distância até à meta/);assert.match(text,/IC95%/);assert.doesNotMatch(text,/Configuração mínima recomendada|não existe configuração viável/i);assert.deepEqual(errors,[]);await page.close()});
