import test from "node:test";
import assert from "node:assert/strict";
import {DEFAULTS, simulate, compare, validateMission, allowedFailureIntervals} from "../engine.js";

const clone = value => structuredClone(value);
const approx = (actual, expected, tolerance=1e-7) => assert.ok(Math.abs(actual-expected)<=tolerance, `${actual} != ${expected}`);

function seeded(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function samples(seed,n){const random=seeded(seed),out=[];for(let i=0;i<n;i++)out.push({cloudDelta:(random()-.5)*35,panelDelta:(random()-.5)*45,socDelta:(random()-.5)*35,fuelFactor:.55+random()*.8,wetFuel:random()<.25,available:random()>.12,surge:.85+random()*.55});return out}
function applySample(base,s){const p=clone(base);p.cloud=Math.min(100,Math.max(20,p.cloud+s.cloudDelta));p.panelDamage=Math.min(90,Math.max(0,p.panelDamage+s.panelDelta));p.initialSoc=Math.min(100,Math.max(20,p.initialSoc+s.socDelta));p.biomassKg*=s.fuelFactor;p.wetFuel=s.wetFuel;p.biomassAvailable=s.available;p.loads.filter(l=>l.critical).forEach(l=>l.surge*=s.surge);return p}
function mc(seed,n=40){return samples(seed,n).map(s=>{const p=applySample(DEFAULTS,s),result=compare(p);return {sample:s,conv:result.convencional.summary,res:result.resiliente.summary,solarEqual:result.convencional.series.every((r,i)=>r.solar===result.resiliente.series[i].solar)}})}

test("energy conservation holds in every interval",()=>{for(const type of ["convencional","resiliente"]){const p=clone(DEFAULTS),dt=p.timeStepHours,r=simulate(p,type);let previous=p.batteryKwh*p.initialSoc/100;for(const row of r.series){const current=row.soc/100*p.batteryKwh,delta=current-previous,served=Object.values(row.served).reduce((a,b)=>a+b,0),chargeInput=delta>0?delta/dt/(p.chargeEfficiency/100):0,batteryOutput=delta<0?-delta/dt*(p.dischargeEfficiency/100):0,residual=row.solar+row.bio+batteryOutput-served-chargeInput;assert.ok(residual>=-1e-7,`negative balance at h${row.t}: ${residual}`);approx(row.unserved,row.demand-served);previous=current}}});
test("battery charge, discharge and reserve limits hold",()=>{for(const p of [clone(DEFAULTS),{...clone(DEFAULTS),batteryKwh:5000},{...clone(DEFAULTS),initialSoc:0}]){const floor=Math.max((1-p.maxDod/100)*p.batteryKwh,p.reserve/100*p.batteryKwh);let previous=p.batteryKwh*p.initialSoc/100;for(const row of simulate(p).series){const current=row.soc/100*p.batteryKwh;assert.ok(current>=floor-1e-7||previous<floor,"battery crossed reserve");assert.ok(row.discharge<=p.maxDischargeKw+1e-7);assert.ok(current-previous<=p.maxChargeKw+1e-7);previous=current}}});
test("15-minute criteria use integer intervals without rounding",()=>{assert.equal(DEFAULTS.timeStepHours,.25);assert.equal(allowedFailureIntervals(288,99),2);assert.equal(allowedFailureIntervals(288,95),14);assert.equal(288-2>=Math.ceil(288*.99),true);assert.equal(288-3>=Math.ceil(288*.99),false);assert.equal(288-14>=Math.ceil(288*.95),true);assert.equal(288-15>=Math.ceil(288*.95),false);const s=simulate(DEFAULTS).summary;assert.deepEqual(s.allowedInterruptions,{health:2,comms:14,continuousBlackout:4})});
test("biomass consumption is exact and no fuel means no generation",()=>{for(const wetFuel of [false,true]){const p={...clone(DEFAULTS),wetFuel},r=simulate(p);r.series.forEach((row,i)=>{approx(row.biomassFuelUsedKg,row.biomassEnergyKwh*p.specificConsumption);if(row.fuelRemaining===0&&i+1<r.series.length)assert.equal(r.series[i+1].bio,0)});approx(r.summary.biomassUsed+r.summary.biomassRemaining,p.biomassKg)}const zero=simulate({...clone(DEFAULTS),biomassKg:0});assert.ok(zero.series.every(r=>r.bio===0&&r.biomassFuelUsedKg===0))});

test("biomass events distinguish exhaustion, daily limit, power and availability",()=>{const limited=simulate({...clone(DEFAULTS),biomassKg:180,dailyFuelLimit:20,solarKw:0,batteryKwh:5,initialSoc:0});const suspensions=limited.events.filter(e=>e.kind==="fuel-limit"),exhaustion=limited.events.filter(e=>e.label.includes("Biomassa esgotada"));assert.ok(suspensions.length>=1);assert.ok(suspensions.every(e=>limited.series.find(r=>r.t===e.t).fuelRemaining>0));assert.equal(exhaustion.length,0);const limitedRow=limited.series.find(r=>r.biomassState==="daily_limit");assert.ok(limitedRow.fuelRemaining>0);assert.ok(limitedRow.biomassHoursRemaining>0);assert.match(limited.events.find(e=>e.kind==="fuel-limit").label,/limite diário atingido; \d+ kg permanecem em reserva/);const empty=simulate({...clone(DEFAULTS),biomassKg:1,dailyFuelLimit:500,solarKw:0,batteryKwh:5,initialSoc:0});assert.ok(empty.events.some(e=>e.label.includes("Biomassa esgotada")));assert.ok(empty.events.filter(e=>e.label.includes("Biomassa esgotada")).every(e=>empty.series.find(r=>Math.abs(r.t-e.t)<.251)?.fuelRemaining===0));const broken=simulate({...clone(DEFAULTS),biomassAvailable:false});assert.ok(broken.series.every(r=>r.biomassState==="unavailable"));});

test("biomass requested, nominal and fuel capacities remain distinct",()=>{const p={...clone(DEFAULTS),biomassKw:4,biomassKg:200,dailyFuelLimit:500,solarKw:0,batteryKwh:5,initialSoc:0};p.loads=p.loads.map(l=>({...l,power:l.power*4}));const r=simulate(p),row=r.series.find(x=>x.biomassRequestedKw>x.biomassNominalKw+.01);assert.ok(row);assert.equal(row.biomassNominalKw,p.biomassKw);assert.ok(row.biomassProducedKw<=row.biomassNominalKw+1e-9);assert.ok(row.biomassProducedKw<=row.biomassFuelPowerCapKw+1e-9);assert.ok(row.biomassProducedKw<=row.biomassDailyPowerCapKw+1e-9);assert.equal(row.biomassState,"power_limited");});
test("priority shedding serves higher priority loads first",()=>{const p=clone(DEFAULTS);p.solarKw=0;p.biomassAvailable=false;p.initialSoc=12.5;p.loads=p.loads.map(l=>({...l,start:0,end:24,surge:1}));const row=simulate(p).series[0];assert.equal(row.served.saude,p.loads.find(l=>l.id==="saude").power);assert.ok(row.served.comms<=p.loads.find(l=>l.id==="comms").power);assert.equal(row.served.outras,0)});
test("first blackout matches first critical deficit",()=>{for(const type of ["convencional","resiliente"]){const r=simulate(DEFAULTS,type),row=r.series.find(x=>x.criticalUnserved>.01);assert.equal(r.summary.firstBlackout,row?.t??null)}});
test("blackout diagnostics compare the same interval and load set",()=>{for(const strategy of ["vida","igual","eficiencia"]){const p={...clone(DEFAULTS),strategy},r=simulate(p);for(const d of r.diagnostics){const row=r.series.find(x=>x.t===d.t);approx(d.unserved,d.demand-d.served);approx(d.affectedDeficit,d.affectedDemand-d.affectedServed);approx(d.criticalDeficit,d.criticalDemand-d.criticalServed);assert.ok(d.usableSupply<row.demand-.01,"blackout despite enough usable supply for all interval demand");assert.ok(d.allocatedTotal<=d.usableSupply+1e-7,"allocation exceeds usable supply");approx(d.allocatedTotal,Object.values(d.allocations).reduce((a,b)=>a+b,0));const claimsDemandExceeded=d.causeCodes.includes("demand_exceeded");assert.equal(claimsDemandExceeded,d.criticalDemand>d.usableSupply+.01,"textual cause contradicts comparable values");if(d.criticalDemand<=d.usableSupply+.01)assert.ok(d.causeCodes.includes("already_allocated"),"missing allocation explanation")}}});
test("paired Monte Carlo conditions and seed reproducibility",()=>{const a=mc(72026),b=mc(72026),c=mc(72027);assert.deepEqual(a,b);assert.ok(a.every(r=>r.solarEqual));assert.notDeepEqual(a.map(r=>r.sample),c.map(r=>r.sample));assert.notDeepEqual(a.map(r=>r.res.criticalUnserved),c.map(r=>r.res.criticalUnserved))});
test("population coverage is deduplicated and uses explicit service thresholds",()=>{const r=simulate(DEFAULTS).summary,c=r.serviceCoverage;assert.equal(r.uniquePeopleProtected,Math.max(c.water,c.comms,c.health));assert.ok(r.uniquePeopleProtected<=DEFAULTS.people);const noDemand=clone(DEFAULTS);noDemand.loads.forEach(l=>l.power=0);const n=simulate(noDemand).summary;assert.equal(n.serviceCoverage.water,0);assert.equal(n.serviceCoverage.comms,DEFAULTS.people);assert.equal(n.serviceCoverage.health,DEFAULTS.healthUsers)});
test("unsafe and incompatible flights are blocked",()=>{const drone={available:true,payload:18,range:70,speed:55,prep:12,maxWind:45},community={distance:20,services:["comms"],serviceEnergy:{comms:0}},kit={service:"comms",usableKwh:.8,totalMassKg:11.2,maxPowerKw:.15,available:1,loadProfile:Array(24).fill(.05)},weather={hour:34,flightWindow:34,wind:30};assert.equal(validateMission(drone,community,weather,kit).ok,true);assert.equal(validateMission(drone,community,{...weather,wind:70},kit).ok,false);assert.equal(validateMission({...drone,range:20},community,weather,kit).ok,false);assert.equal(validateMission({...drone,payload:5},community,weather,kit).ok,false);assert.equal(validateMission(drone,community,{...weather,hour:71,flightWindow:80},kit).ok,false);assert.equal(validateMission(drone,community,weather,{...kit,service:"water"}).ok,false)});
test("extreme resource and demand scenarios remain finite",()=>{const cases=[];let p=clone(DEFAULTS);p.solarKw=0;cases.push(p);p=clone(DEFAULTS);p.biomassKg=0;cases.push(p);p=clone(DEFAULTS);p.initialSoc=0;cases.push(p);p=clone(DEFAULTS);p.batteryKwh=10000;cases.push(p);p=clone(DEFAULTS);p.loads.forEach(l=>l.power=0);cases.push(p);p=clone(DEFAULTS);p.loads.forEach(l=>l.power=1000);cases.push(p);p=clone(DEFAULTS);p.wetFuel=true;cases.push(p);p=clone(DEFAULTS);p.biomassAvailable=false;cases.push(p);p=clone(DEFAULTS);Object.assign(p,{solarKw:200,batteryKwh:1000,biomassKw:100,biomassKg:5000,initialSoc:100});cases.push(p);for(const [i,input] of cases.entries()){const r=simulate(input);assert.equal(r.series.length,288);for(const row of r.series)for(const value of [row.solar,row.bio,row.demand,row.soc,row.unserved,row.fuelRemaining])assert.ok(Number.isFinite(value),`case ${i}`)}});
test("zero solar produces no solar energy",()=>{const r=simulate({...clone(DEFAULTS),solarKw:0});assert.ok(r.series.every(x=>x.solar===0))});
test("empty battery never creates battery energy",()=>{const p={...clone(DEFAULTS),initialSoc:0,solarKw:0,biomassAvailable:false},r=simulate(p);assert.ok(r.series.every(x=>x.discharge===0&&x.soc===0))});
test("very large battery respects its capacity",()=>{const p={...clone(DEFAULTS),batteryKwh:10000,initialSoc:100},r=simulate(p);assert.ok(r.series.every(x=>x.soc<=100+1e-9))});
test("zero demand produces no unserved energy",()=>{const p=clone(DEFAULTS);p.loads.forEach(l=>l.power=0);const r=simulate(p);assert.ok(r.series.every(x=>x.demand===0&&x.unserved===0))});
test("demand above all generation is detected",()=>{const p={...clone(DEFAULTS),solarKw:0,biomassAvailable:false,initialSoc:0};p.loads.forEach(l=>{l.power=1000;l.start=0;l.end=24;l.surge=1});const r=simulate(p);assert.equal(r.summary.firstBlackout,0);assert.ok(r.summary.criticalUnserved>0)});
test("wet fuel derates generator power",()=>{const base=clone(DEFAULTS);base.loads.forEach(l=>{l.power=20;l.start=0;l.end=24;l.surge=1});const dry=simulate({...base,wetFuel:false}).series[0],wet=simulate({...base,wetFuel:true}).series[0];assert.ok(wet.bio<dry.bio);assert.ok(wet.biomassHumidityReductionKw>0)});
test("broken generator never produces",()=>{const r=simulate({...clone(DEFAULTS),biomassAvailable:false});assert.ok(r.series.every(x=>x.bio===0&&x.biomassFuelUsedKg===0))});
test("all resources available are evaluated without forced success",()=>{const p={...clone(DEFAULTS),solarKw:200,batteryKwh:1000,biomassKw:100,biomassKg:5000,initialSoc:100,biomassAvailable:true,wetFuel:false},r=simulate(p);assert.equal(typeof r.summary.survival.joint,"boolean");assert.ok(r.series.every(x=>x.unserved>=0&&x.soc<=100+1e-9))});
